version: 2
project_name: fabbro

builds:
  - main: ./cmd/fabbro
    binary: fabbro
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude: ['^docs:', '^chore:', '^style:', '^test:', '^refactor:']
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1

brews:
  - name: fabbro
    repository:
      owner: charly-vibes
      name: homebrew-charly
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/charly-vibes/fabbro"
    description: "Local-first code review annotation tool with a terminal UI"
    license: "MIT"
    test: |
      system "#{bin}/fabbro", "--version"

scoops:
  - name: fabbro
    repository:
      owner: charly-vibes
      name: scoop-charly
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: bucket
    homepage: "https://github.com/charly-vibes/fabbro"
    description: "Local-first code review annotation tool with a terminal UI"
    license: "MIT"

release:
  github:
    owner: charly-vibes
    name: fabbro
  prerelease: auto
  name_template: "{{ .Tag }}"
